[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "src/=src/",
  "oz/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/=node_modules/@chainlink/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
