[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "src/=src/",
  "forge-std/=lib/forge-std/src/",
  "oz/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/=node_modules/@chainlink/",
  "balancer-v3-interfaces/=lib/balancer-v3-monorepo/pkg/interfaces/contracts/",
  "balancer-v2-interfaces/=lib/balancer-v2-monorepo/pkg/interfaces/contracts/",
  "balancer-v3/=lib/balancer-v3-monorepo/",
  "gyro-concentrated-lps-balv2/=lib/gyro-concentrated-lps-balv2/",
  # For tests only
  "permit2/=lib/permit2/src/",
  # Some remappings for compat with older code used for testing.
  "@balancer-labs/v2-solidity-utils/=lib/balancer-v2-monorepo/pkg/solidity-utils/",
  "@balancer-labs/v2-pool-utils/=lib/balancer-v2-monorepo/pkg/pool-utils/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
]

[fmt]
line_length = 100
tab_width = 4
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
