[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "src/=src/",
  "oz/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/=node_modules/@chainlink/",
  "balancer-v3-interfaces/=lib/balancer-v3-monorepo/pkg/interfaces/contracts/",
  "balancer-v3/=lib/balancer-v3-monorepo/",
  "gyro-concentrated-lps-balv2/=lib/gyro-concentrated-lps-balv2/",
]

[fmt]
line_length = 100
tab_width = 4
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
